config/routes.rb
Rails.application.routes.draw do
    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
    resources :lists do
      resources :tasks, except: [:index, :show]
    end

    get '/overdue', to: 'overdue#index'


    root 'welcome#home'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  belongs_to :user

  validates :name, presence: true
  validates :due_date, presence: true

  scope :over_due, -> { where('due_date <= ?', Date.today)}

  def task_attributes=(task_attributes)
    if task_attributes[:name].present?
      self.tasks.build(task_attributes)
    end
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list
  validates :name, presence: true

  scope :incomplete, -> { where(complete: false)}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :lists
  has_many :tasks, through: :lists
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]
  validates :email, uniqueness: true
  validates :password, length: { minimum: 8 }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || root_path
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!

  def index
    @lists = current_user.lists.all
  end

  def show
    @list = current_user.lists.find(params[:id])
  end

  def new
    @list = current_user.lists.build
  end

  def edit
    @list = current_user.lists.find(params[:id])
  end

  def create
    @list = current_user.lists.build(list_params)
    if @list.save
      redirect_to lists_path(@list)
    else
      flash[:notice] = "Error"
      render 'new'
    end
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_params)
    redirect_to lists_path(@list)
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :due_date, :task_attributes => [:name, :complete])
  end
end

app/controllers/overdue_controller.rb
class OverdueController < ApplicationController

  def index
    @lists = current_user.lists.over_due
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!

  def index
    @list = List.find(params[:list_id])
    @tasks = @list.tasks
    respond_to do |format|
      format.html { render :index}
      format.json { render json: @tasks}
    end
  end

  def show

  end

  def new
    @list = List.find(params[:list_id])
    @task = @list.tasks.build
  end

  def edit
    @list = List.find(params[:list_id])
    puts @list.id
    @task = Task.find(params[:id])
  end

  def create
    @list = List.find(params[:list_id])
    @task = @list.tasks.build(task_params)
    if @task.save
      # redirect_to list_path(@list)
      render json: @task, status: 201

    else
      flash[:notice] = "Error"
      render 'new'
    end
  end

  def update
    @list = List.find(params[:list_id])
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to list_path(@list)
  end

  def destroy
    puts params.inspect
    @list = List.find(params[:list_id])
    puts @list.id
    @task = @list.tasks.find(params[:id])
    puts @task.id
    @task.destroy
    redirect_to list_path(@list)
  end

  private

  def task_params
    params.require(:task).permit(:name, :complete)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    !!current_user
  end  
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def resource_class
    devise_mapping.to
  end 
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to "Home", root_path%></li>
      <li><%= link_to "View All Task Lists", lists_path%></li>
      <li><%= link_to "New Task List", new_list_path%></li>
      <li><%= link_to "Sign out", destroy_user_session_path, method: 'delete' %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css" rel="stylesheet" type="text/css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>



    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center">
          <h1 class="welcome color-white">Welcome to the <span>Task</span> app!</h1>
          <ul>
            <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
            <%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
            <%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>
          </ul>  
        </div>
      </div>
    </div>



    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>
  <%= f.text_field :name, placeholder: "Name", class: "form-control"%>
  <%= f.date_field :due_date, placeholder:"Due Date", class: "form-control" %>

  <%= f.fields_for :task_attributes do |task| %>

  <%= task.text_field :name, placeholder:"Add a Task", class: "form-control" %>
  <p><span class="task-list-text complete-text">Complete?   </span><%= task.check_box :complete %></p>
  
  <% end %>

  <%= f.submit class: "form-control btn-main sign-up" %>
<% end %>

app/views/lists/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4 col-sm-12 bg-white">
      <%= render "layouts/nav" %>
      <h1 class="text-center log-in">Edit Your List</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4 col-sm-12 bg-white">

      <%= render 'layouts/nav' %>

      <div>
        <h1 class="log-in text-center">Task List</h1>
        <hr>
        <% @lists.each do |list| %>
          <ul>
            <li class="over-flow">
              <p class="task-list-text display-inline"><%= list.name %></p>

              <div class="float-right">
                <p class="task-list-text display-inline">Due Date</p>
              </div>

              <div role="group" aria-label="...">
                <%= button_to "View Tasks", list_path(list), method: 'get', class: "button-small btn light-blue"%>
                <%= button_to "Edit", edit_list_path(list), method: 'get', class: "button-small btn light-green"%>
                <%= button_to "Delete", list_path(list), method: 'delete', class: "button-small btn"%>
                <p class="task-list-text due-date display-inline"><%= list.due_date.strftime("%B %d, %Y")%></p>
              </div>
            </li>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4 col-sm-12 bg-white">
      <%= render "layouts/nav" %>
      <h1 class="text-center log-in">Create Your List</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4 col-sm-12 bg-white">

      <%= render 'layouts/nav' %>

      <div>
        <h1 class="list-name log-in text-center"><%= @list.name %></h1>
        <hr>
        <div class="clearfix">
          <a href="#" class="js-next text-center form-control btn-main sign-up next-button" data-id="<%=@list.id%>">Next List</a>
        </div>
        <p class="task-list-text"><span class="bold-text">Due Date: </span><span class="float-right due-date"><%= @list.due_date.strftime("%B %d, %Y")%></span></p>
        <p class="task-list-text"><span class="border-bottom bold-text">Tasks</span><span class="task-list-tesk float-right border-bottom bold-text">Completed?</span></p>

        <div class="task-div">
        <% @list.tasks.each do |task| %>
          <ul>
            <li class="over-flow">

              <p class="task-name task-list-text display-inline"><%= task.name %></p>


              <div class="float-right">
                <p class="task-list-text display-inline"><%= check_box_tag 'completed?', 1, task.complete, disabled: true, id: "task_complete" %></p>
              </div>

              <div role="group" aria-label="...">
                <%= button_to "Edit", edit_list_task_path(@list,task), method: 'get', class: "button-small btn light-green"%>
                <%= button_to "Delete", list_task_path(@list,task), method: 'delete', class: "button-small btn"%>
              </div>

            </li>
          </ul>
        <% end %>
      </div>

      </div>

      <div class="new-task-div">
      </div>
      <div class="create-task">
      <h1 class="text-center log-in">Create Your Task</h1>

      </div>
        <a href="#" class="new-task text-center form-control btn-main margin-top-25" data-id="<%=@list.id%>">New Task</a>
    </div>
  </div>
</div>
<script type="text/javascript" charset="utf-8">

$(function () {
  token = '<%= form_authenticity_token %>';
  nextTaskList();
  newTaskShow(token);

});

function nextTaskList () {
  $(".js-next").on("click", function (event) {
    event.preventDefault();


    $(".new-task-div").html("")
    $(".create-task").html("")
    token = '<%= form_authenticity_token %>';
    newTaskShow(token);

    var getId = parseInt($(".js-next").attr("data-id"))

    var listIdChecker = <%= @listid %>

    var currentId=listIdChecker.indexOf(getId)

    var nextId = listIdChecker[currentId+1]

    if (listIdChecker.length - 1 === currentId ) {
      nextId = listIdChecker[0]
    }

    var setId = $(".js-next").attr("data-id", nextId)


    window.history.pushState('next', 'Title', '/lists/' + nextId);


    $.get("/lists/" + nextId + ".json", function(data) {


      var list = data;

      var date = list["due_date"]
      var name = list["name"]
      var listId = list["id"]
      var tasks = list["tasks"]

      var newList = new List(name, date, listId)

      $(".list-name").text(newList.name)
      $(".due-date").text(newList.date())

      $(".js-next").attr("data-id", newList.id);

      getTaskInfo(tasks, newList);

    })
    .fail(function(){

      alert("sorry")
    })

  });
}

function getTaskInfo (tasks, list) {
   $(".task-div").html("");

  token = '<%= form_authenticity_token %>';

  for (i = 0; i < tasks.length; i++){

    var newTask = new Task(tasks[i].name, tasks[i].complete, tasks[i].id)

    $(".task-div").append(appendNewTask (newTask, list.id, token))

  }

}

function newTask () {
  $('form.task-form').submit(function(event) {

    event.preventDefault();

    var values = $(this).serialize();
    currentUrlId = window.location.pathname
    var posting = $.post(currentUrlId + '/tasks', values);

    posting.done(function(data){
      token = '<%= form_authenticity_token %>';

      $(".create-task").hide(1000)

      var myTask = data;

      var newTasks = new Task(myTask.name, myTask.complete, myTask.id)

      $(".new-task-div").append(appendNewTask (newTasks, myTask.list.id, token ))
    })


  })
}


</script>

app/views/overdue/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4 col-sm-12 bg-white">


      <div>
        <h1 class="log-in text-center">Overdue Task List</h1>
        <hr>
       <% @lists.each do |list| %>
          <ul>
            <li class="over-flow">
              <p class="task-list-text display-inline"><%= list.name %></p>

              <div class="float-right">
                <p class="task-list-text display-inline">Due Date</p>
              </div>

              <div role="group" aria-label="...">
                <%= button_to "View Tasks", list_path(list), method: 'get', class: "button-small btn light-blue"%>
                <%= button_to "Edit", edit_list_path(list), method: 'get', class: "button-small btn light-green"%>
                <%= button_to "Delete", list_path(list), method: 'delete', class: "button-small btn"%>
                <p class="task-list-text due-date display-inline"><%= list.due_date.strftime("%B %d, %Y")%></p>
              </div>
            </li>
          </ul>

        <% end %>
        
      </div>
    </div>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_for ([@list, @list.tasks.build]), :html => {:class => 'task-form'}  do |f|%>
  <%= f.text_field :name, placeholder: "Name", class: "form-control" %>
  <p><span class="task-list-text complete-text">Complete?   </span><%= f.check_box :complete %></p>
  <%= f.submit class: "form-control btn-main sign-up", :data => { disable_with: false } %>
<% end %>

app/views/tasks/_form2.html.erb
<%= form_for ([@list, @task])  do |f|%>
  <%= f.text_field :name, placeholder: "Name", class: "form-control" %>
  <p><span class="task-list-text complete-text">Complete?   </span><%= f.check_box :complete %></p>
  <%= f.submit class: "form-control btn-main sign-up" %>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4 col-sm-12 bg-white">
      <%= render "layouts/nav" %>
      <h1 class="text-center log-in">Edit Your Task</h1>
      <%= render 'form2' %>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<h1><%=@list.name %></h1><br><br>
<% @tasks.each do |task| %>
<hr>
<%= task.complete %><br>
<%= task.name %><br>
<%= link_to "Delete", [@list, task], method: 'delete'%><br>
<hr>
<% end %>

app/views/tasks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4 col-sm-12 bg-white">
      <%= render "layouts/nav" %>
      <h1 class="text-center log-in">Create Your Task</h1>
      <%= render 'tasks/form2' %>
    </div>
  </div>
</div>

app/views/welcome/home.html.erb
<div>
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4 col-sm-12 bg-white">
        <% if logged_in? %>
          <div>
            <%= render "layouts/nav" %>
            <%= link_to "View All Task Lists", lists_path, class: "text-center form-control btn-main margin-top-25"%>
            <%= link_to "New Task List", new_list_path, class: "text-center form-control btn-main sign-up"%>
          </div>
        <% else %>
        <div class="text-center">

          <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#login" aria-controls="login" role="tab" data-toggle="tab">Log In</a></li>
            <li role="presentation"><a href="#signup" aria-controls="signup" role="tab" data-toggle="tab">Sign Up</a></li>
          </ul>

          <!-- Tab panes -->
          <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="login">
              <h1 class="log-in">Please Log In</h1>
              <%= render 'devise/sessions/new' %>
            </div>
            <div role="tabpanel" class="tab-pane" id="signup">
              <h1 class="log-in">Please Sign Up</h1>
              <%= render 'devise/registrations/new' %>
            </div>
          </div>
        </div>
        <% end %>

      </div>
    </div>
  </div>
</div>